### PR TITLE
Updated projects text

### PR DESCRIPTION
**Pull request by mialondon**
Task descriptions need improving but it's a start. Are tasks bounced back to the pool/queue if the results don't match?

### CODE REVIEW

**Comment by alexandermendes** [comment]
We'll still need to decide on the process for non-matched tasks but I'm thinking this will probably be a third project type. So something like **mark > transcribe > verify**, where verify obviously includes only the ones that couldn't be matched automatically.

**Comment by alexandermendes** [comment]
Again, can update this text later as the final process is decided, merging for now!

**Comment by mialondon** [comment]
We could ask people interested in the 'verify' task to get in touch or post on the forum in the meantime?

**Comment by alexandermendes** [comment]
Sure, probably a good topic for a forum post when everything is up and running. It would be good to inspire a bit more activity there.

**Pull request merged**
